version: "3"
services:
  node-app:
    container_name: express-node-container
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    depends_on:
      - postgres
  #postgres:
   # image: postgres
   # restart: always
   # volumes:
     # - postgres-db:/var/lib/postgresql/data
    #environment:
     # POSTGRES_USER: root
     # POSTGRES_PASSWORD: example
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  apache:
    image: httpd:2.4
    ports:
      - "80:80"
    volumes:
      - ./:/usr/local/apache2/htdocs/
    depends_on:
      - node-app
    
  #mongo-express:
   # image: mongo-express
   # restart: always
   # ports:
    #  - 8081:8081
    #environment:
     # ME_CONFIG_MONGODB_ADMINUSERNAME: root
     # ME_CONFIG_MONGODB_ADMINPASSWORD: example
     # ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    #depends_on:
     # - mongo
  redis:
    image: redis  
volumes:
  mongo-db:
  postgres-db: